SKILLS = [
    "python",
    "django",
    "fastapi",
    "flask",
    "docker",
    "kubernetes",
    "terraform",
    "aws",
    "azure",
    "gcp",
    "postgresql",
    "mysql",
    "mongodb",
    "redis",
    "celery",
    "jenkins",
    "github actions",
    "gitlab ci/cd",
    "prometheus",
    "grafana",
    "elk",
    "nginx",
    "linux",
    "microservices",
    "rest api",
    "rabbitmq",
    "argocd",
    "helm",
    "ansible",
    "devops",
    "ci/cd"
]